#!/bin/bash
# 演示不同主题的效果

cd "$(dirname "$0")/.."

echo "🎨 Flow Observer 主题演示"
echo ""
echo "=== 深色主题 ==="
echo "  tokyo-night       - 深蓝灰色主题（默认）"
echo "  nord              - 冷色系蓝灰主题"
echo "  catppuccin        - 温暖的紫粉色主题 ⭐"
echo "  dracula           - 经典紫色主题"
echo "  gruvbox           - 复古暖色主题 🔥"
echo "  solarized         - 经典低对比度主题"
echo "  one-dark          - Atom 编辑器主题"
echo ""
echo "=== 浅色主题 ☀️ ==="
echo "  solarized-light   - 经典米黄色浅色主题"
echo "  gruvbox-light     - 复古暖色浅色主题"
echo "  catppuccin-latte  - 温暖的浅色主题 ⭐"
echo "  github-light      - GitHub 白色主题"
echo ""
echo "=== 彩色主题 🌈 ==="
echo "  monokai           - 经典鲜艳主题"
echo "  synthwave         - 赛博朋克风格 💜"
echo "  ocean             - 海洋蓝主题 🌊"
echo ""
echo "要切换主题，请选择一个主题并运行："
echo ""
echo "  FLOW_THEME=catppuccin ./scripts/flow-run.sh"
echo ""
echo "或在 flow 右栏 observer 内重启（Zellij 分屏）："
echo ""
echo "  Ctrl-C 后执行: FLOW_THEME=gruvbox bun run src/main.ts --live"
echo "  （左栏 Claude 不受影响；整会话可用 FLOW_THEME=gruvbox ./scripts/flow-run.sh）"
echo ""
